[build]
command = "echo 'No build needed'"
publish = "public"
functions = "functions"  # 确保函数目录正确指向 `functions` 文件夹

[[redirects]]
from = "/api/*"          # 匹配所有 /api/ 开头的路径（包括 /api 和 /api/1451001600000）
to = "/.netlify/functions/api?date=:splat"  # 将路径中的日期部分作为 `date` 查询参数传递
status = 200             # 200 状态码表示代理请求（非重定向）