name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove old origin
        run: |
          git remote rm origin || true
          git remote add origin https://x-access-token:${{ secrets.Niyv0710 }}@github.com/Niyv0708/timestamp-microservice.git

      - name: Deploy using GH-Pages Action
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.Niyv0710 }}
          publish_dir: ./public
          publish_branch: gh-pages